baseurl = "http://cognition.ca"
languageCode = "en-us"
title = "Cognition"
publishdir = "./"
theme = "hyde"
copyright = "Copyright Joshua McKenty."

[params]
Description = "Juggling, Technology, Life."
Copyright = "(c) Joshua McKenty, 2014."
